services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - INDEX_PATH=/data/hnsw_index.bin
      - MAPPING_PATH=/data/id_mapping.json
    ports:
      - "5001:5001"
    networks:
      - orchara-network
    volumes:
      - orchara-database_index-data:/data
    command: uvicorn main:app --host 0.0.0.0 --port 5001 --workers 4 --reload

networks:
  orchara-network:
    external: true
    name: orchara-database_default

volumes:
  orchara-database_index-data:
    external: true 